spring:
  zipkin:
    base-url: http://zipkin:9411 # Property needed only if it is running in docker

cxf:
  path: /
  jaxrs:
    component-scan: true
    classes-scan-packages: com.schubergphilis.rest
    client:
      address: http://service-4:8085
      classes-scan-packages: com.schubergphilis.rest
      thread-safe: true

server:
  port: 8084

logging:
  level:
    org.springframework.cloud.sleuth.log: TRACE