spring:
  zipkin:
    base-url: http://zipkin:9411 # Property needed only if it is running in docker

service4:
  url: http://service-4:8085

cxf:
  path: /
  jaxrs:
    component-scan: true
    classes-scan-packages: com.schubergphilis.rest

server:
  port: 8084

logging:
  level:
    org.springframework.cloud.sleuth.log: TRACE
#trace: true
