spring:
  zipkin:
    base-url: http://zipkin:9411 # Property needed only if it is running in docker
  sleuth:
    sampler:
      percentage: 1.0
    enabled: true

cxf:
  path: /
  jaxrs:
    component-scan: true
    classes-scan-packages: com.schubergphilis.rest

server:
  port: 8085